# Generated by Django 5.0.3 on 2024-03-20 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('type', models.CharField(choices=[('RAN', 'RAN'), ('CORE', 'CORE'), ('IT', 'IT')], max_length=100)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oai_helm_chart_name', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=50)),
                ('version', models.TextField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helm.application')),
            ],
        ),
    ]
