# Generated by Django 5.2.5 on 2025-08-26 08:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KubernetesCluster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(help_text="Kubernetes API server endpoint"),
                ),
                ("api_version", models.CharField(default="v1.29", max_length=20)),
                (
                    "auth_method",
                    models.CharField(
                        choices=[
                            ("token", "Bearer Token"),
                            ("cert", "Client Certificate"),
                            ("kubeconfig", "Kubeconfig File"),
                            ("service_account", "Service Account"),
                        ],
                        default="kubeconfig",
                        max_length=20,
                    ),
                ),
                (
                    "kubeconfig_data",
                    models.TextField(
                        blank=True, help_text="Base64 encoded kubeconfig file"
                    ),
                ),
                (
                    "bearer_token",
                    models.TextField(blank=True, help_text="Encrypted bearer token"),
                ),
                (
                    "client_cert",
                    models.TextField(
                        blank=True, help_text="Encrypted client certificate"
                    ),
                ),
                (
                    "client_key",
                    models.TextField(blank=True, help_text="Encrypted client key"),
                ),
                (
                    "ca_cert",
                    models.TextField(blank=True, help_text="Encrypted CA certificate"),
                ),
                ("cluster_version", models.CharField(blank=True, max_length=50)),
                ("node_count", models.IntegerField(default=0)),
                ("supports_helm", models.BooleanField(default=True)),
                ("supports_operators", models.BooleanField(default=True)),
                (
                    "default_namespace",
                    models.CharField(default="default", max_length=63),
                ),
                ("max_pods_per_node", models.IntegerField(default=110)),
                ("max_namespaces", models.IntegerField(default=100)),
                ("storage_classes", models.JSONField(default=list)),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("ERROR", "Error"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                ("last_health_check", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeploymentDescriptor",
            fields=[
                (
                    "descriptor_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("kubernetes", "Kubernetes Profile"),
                            ("etsi_nfv", "ETSI NFV Profile"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "artifact_source_type",
                    models.CharField(
                        choices=[
                            ("helm_repo", "Helm Repository"),
                            ("github", "GitHub Repository"),
                            ("oci", "OCI Registry"),
                            ("local", "Local Path"),
                        ],
                        default="helm_repo",
                        max_length=20,
                    ),
                ),
                ("artifact_chart_path", models.CharField(blank=True, max_length=200)),
                ("artifact_repo_url", models.URLField()),
                ("artifact_name", models.CharField(max_length=200)),
                ("artifact_version", models.CharField(default="latest", max_length=50)),
                ("input_params", models.JSONField(default=dict)),
                ("required_cpu_cores", models.IntegerField(default=1)),
                ("required_memory_gb", models.IntegerField(default=1)),
                ("required_storage_gb", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("additional_params", models.JSONField(blank=True, default=dict)),
                (
                    "target_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployment_descriptors",
                        to="sol003.kubernetescluster",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NfDeploymentInstance",
            fields=[
                (
                    "instance_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "instantiation_state",
                    models.CharField(
                        choices=[
                            ("NOT_INSTANTIATED", "Not Instantiated"),
                            ("INSTANTIATING", "Instantiating"),
                            ("INSTANTIATED", "Instantiated"),
                            ("TERMINATING", "Terminating"),
                            ("TERMINATED", "Terminated"),
                            ("ERROR", "Error"),
                        ],
                        default="NOT_INSTANTIATED",
                        max_length=20,
                    ),
                ),
                (
                    "deployment_namespace",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "helm_release_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vm_instances", models.JSONField(blank=True, default=list)),
                ("smo_callback_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "descriptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="sol003.deploymentdescriptor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KubernetesDeployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=63)),
                ("deployment_name", models.CharField(max_length=63)),
                ("helm_release_name", models.CharField(blank=True, max_length=63)),
                ("deployed_manifests", models.JSONField(default=list)),
                ("helm_values", models.JSONField(default=dict)),
                ("pods_ready", models.IntegerField(default=0)),
                ("pods_desired", models.IntegerField(default=1)),
                ("services_created", models.JSONField(default=list)),
                ("ingress_urls", models.JSONField(default=list)),
                (
                    "kubernetes_status",
                    models.CharField(
                        choices=[
                            ("DEPLOYING", "Deploying"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("SCALING", "Scaling"),
                            ("UPDATING", "Updating"),
                            ("TERMINATING", "Terminating"),
                        ],
                        default="DEPLOYING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "k8s_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="sol003.kubernetescluster",
                    ),
                ),
                (
                    "nf_instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="k8s_deployment",
                        to="sol003.nfdeploymentinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VnfLcmOperation",
            fields=[
                (
                    "operation_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("INSTANTIATE", "Instantiate"),
                            ("TERMINATE", "Terminate"),
                            ("HEAL", "Heal"),
                            ("SCALE", "Scale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "operation_state",
                    models.CharField(
                        choices=[
                            ("STARTING", "Starting"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED_TEMP", "Failed Temporarily"),
                            ("FAILED", "Failed"),
                            ("ROLLING_BACK", "Rolling Back"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="STARTING",
                        max_length=20,
                    ),
                ),
                ("operation_params", models.JSONField(default=dict)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("rollback_on_failure", models.BooleanField(default=True)),
                ("rollback_executed", models.BooleanField(default=False)),
                ("state_snapshot", models.JSONField(blank=True, default=dict)),
                ("execution_attempts", models.JSONField(default=list)),
                ("automatic_rollback", models.BooleanField(default=True)),
                (
                    "vnf_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="sol003.nfdeploymentinstance",
                    ),
                ),
            ],
        ),
    ]
