# Generated by Django 5.2.5 on 2025-08-26 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kubernetescluster',
            old_name='id',
            new_name='cloud_id',
        ),
    ]
