# Generated by Django 5.2.5 on 2025-08-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0002_rename_id_kubernetescluster_cloud_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetescluster',
            name='api_endpoint',
            field=models.URLField(help_text='Kubernetes API server endpoint', unique=True),
        ),
    ]
