# Generated by Django 5.2.5 on 2025-09-01 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0003_alter_kubernetescluster_api_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfdeploymentinstance',
            name='descriptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='sol003.deploymentdescriptor'),
        ),
    ]
