# Generated by Django 5.2.5 on 2025-09-01 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sol003", "0004_alter_nfdeploymentinstance_descriptor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentdescriptor",
            name="target_cluster",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deployment_descriptors",
                to="sol003.kubernetescluster",
            ),
        ),
        migrations.AlterField(
            model_name="nfdeploymentinstance",
            name="descriptor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instances",
                to="sol003.deploymentdescriptor",
            ),
        ),
    ]
