# Generated by Django 5.2.5 on 2025-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0005_alter_deploymentdescriptor_target_cluster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentdescriptor',
            name='homing',
            field=models.BooleanField(default=True),
        ),
    ]
