# Generated by Django 5.2.5 on 2025-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sol003", "0006_deploymentdescriptor_homing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentdescriptor",
            name="homing",
            field=models.BooleanField(default=False),
        ),
    ]
