# Generated by Django 5.2.5 on 2025-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sol003", "0007_alter_deploymentdescriptor_homing"),
    ]

    operations = [
        migrations.AddField(
            model_name="kubernetescluster",
            name="prometheus_endpoint",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
