# Generated by Django 5.2.5 on 2025-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0008_kubernetescluster_prometheus_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetescluster',
            name='cloud_name',
            field=models.CharField(default='O-Cloud-00', max_length=50),
            preserve_default=False,
        ),
    ]
