# Generated by Django 5.2.5 on 2025-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol003', '0009_kubernetescluster_cloud_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetescluster',
            name='cloud_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
