# Generated by Django 5.2.5 on 2025-11-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sol003", "0010_alter_kubernetescluster_cloud_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentdescriptor",
            name="artifact_repo_branch",
            field=models.CharField(default="master", max_length=200),
            preserve_default=False,
        ),
    ]
