# Generated by Django 5.0.3 on 2024-03-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFOModel',
        ),
    ]
